/*
 * Copyright (c) 2018 Oticon A/S
 * Copyright (c) 2020-2023 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#define NRF_FICR_NS_BASE_REAL_HW                  0x00FFC000UL
#define NRF_UICR_S_BASE_REAL_HW                   0x00FFD000UL
#define NRF_SICR_S_BASE_REAL_HW                   0x00FFE000UL
#define NRF_CRACENCORE_S_BASE_REAL_HW             0x50010000UL
#define NRF_USBHSCORE_NS_BASE_REAL_HW             0x40020000UL
#define NRF_USBHSCORE_S_BASE_REAL_HW              0x50020000UL
#define NRF_SPU00_S_BASE_REAL_HW                  0x50040000UL
#define NRF_MPC00_S_BASE_REAL_HW                  0x50041000UL
#define NRF_DPPIC00_NS_BASE_REAL_HW               0x40042000UL
#define NRF_DPPIC00_S_BASE_REAL_HW                0x50042000UL
#define NRF_PPIB00_NS_BASE_REAL_HW                0x40044000UL
#define NRF_PPIB00_S_BASE_REAL_HW                 0x50044000UL
#define NRF_PPIB01_NS_BASE_REAL_HW                0x40045000UL
#define NRF_PPIB01_S_BASE_REAL_HW                 0x50045000UL
#define NRF_KMU_S_BASE_REAL_HW                    0x50049000UL
#define NRF_AAR00_NS_BASE_REAL_HW                 0x4004A000UL
#define NRF_CCM00_NS_BASE_REAL_HW                 0x4004A000UL
#define NRF_AAR00_S_BASE_REAL_HW                  0x5004A000UL
#define NRF_CCM00_S_BASE_REAL_HW                  0x5004A000UL
#define NRF_ECB00_NS_BASE_REAL_HW                 0x4004B000UL
#define NRF_ECB00_S_BASE_REAL_HW                  0x5004B000UL
#define NRF_VPR00_NS_BASE_REAL_HW                 0x4004C000UL
#define NRF_VPR00_S_BASE_REAL_HW                  0x5004C000UL
#define NRF_SPIM00_NS_BASE_REAL_HW                0x4004D000UL
#define NRF_SPIS00_NS_BASE_REAL_HW                0x4004D000UL
#define NRF_UARTE00_NS_BASE_REAL_HW               0x4004D000UL
#define NRF_SPIM00_S_BASE_REAL_HW                 0x5004D000UL
#define NRF_SPIS00_S_BASE_REAL_HW                 0x5004D000UL
#define NRF_UARTE00_S_BASE_REAL_HW                0x5004D000UL
#define NRF_GLITCHDET_S_BASE_REAL_HW              0x5004E000UL
#define NRF_RRAMC_S_BASE_REAL_HW                  0x5004E000UL
#define NRF_P2_NS_BASE_REAL_HW                    0x40050400UL
#define NRF_GPIOHSPADCTRL_S_BASE_REAL_HW          0x50050400UL
#define NRF_P2_S_BASE_REAL_HW                     0x50050400UL
#define NRF_CTRLAP_NS_BASE_REAL_HW                0x40052000UL
#define NRF_CTRLAP_S_BASE_REAL_HW                 0x50052000UL
#define NRF_TAD_NS_BASE_REAL_HW                   0x40053000UL
#define NRF_TAD_S_BASE_REAL_HW                    0x50053000UL
#define NRF_TIMER00_NS_BASE_REAL_HW               0x40055000UL
#define NRF_TIMER00_S_BASE_REAL_HW                0x50055000UL
#define NRF_EGU00_NS_BASE_REAL_HW                 0x40058000UL
#define NRF_EGU00_S_BASE_REAL_HW                  0x50058000UL
#define NRF_CRACEN_S_BASE_REAL_HW                 0x50059000UL
#define NRF_USBHS_NS_BASE_REAL_HW                 0x4005A000UL
#define NRF_USBHS_S_BASE_REAL_HW                  0x5005A000UL
#define NRF_SPU10_S_BASE_REAL_HW                  0x50080000UL
#define NRF_DPPIC10_NS_BASE_REAL_HW               0x40082000UL
#define NRF_DPPIC10_S_BASE_REAL_HW                0x50082000UL
#define NRF_PPIB10_NS_BASE_REAL_HW                0x40083000UL
#define NRF_PPIB10_S_BASE_REAL_HW                 0x50083000UL
#define NRF_PPIB11_NS_BASE_REAL_HW                0x40084000UL
#define NRF_PPIB11_S_BASE_REAL_HW                 0x50084000UL
#define NRF_TIMER10_NS_BASE_REAL_HW               0x40085000UL
#define NRF_TIMER10_S_BASE_REAL_HW                0x50085000UL
#define NRF_EGU10_NS_BASE_REAL_HW                 0x40087000UL
#define NRF_EGU10_S_BASE_REAL_HW                  0x50087000UL
#define NRF_RADIO_NS_BASE_REAL_HW                 0x4008A000UL
#define NRF_RADIO_S_BASE_REAL_HW                  0x5008A000UL
#define NRF_SPU20_S_BASE_REAL_HW                  0x500C0000UL
#define NRF_DPPIC20_NS_BASE_REAL_HW               0x400C2000UL
#define NRF_DPPIC20_S_BASE_REAL_HW                0x500C2000UL
#define NRF_PPIB20_NS_BASE_REAL_HW                0x400C3000UL
#define NRF_PPIB20_S_BASE_REAL_HW                 0x500C3000UL
#define NRF_PPIB21_NS_BASE_REAL_HW                0x400C4000UL
#define NRF_PPIB21_S_BASE_REAL_HW                 0x500C4000UL
#define NRF_PPIB22_NS_BASE_REAL_HW                0x400C5000UL
#define NRF_PPIB22_S_BASE_REAL_HW                 0x500C5000UL
#define NRF_SPIM20_NS_BASE_REAL_HW                0x400C6000UL
#define NRF_SPIS20_NS_BASE_REAL_HW                0x400C6000UL
#define NRF_TWIM20_NS_BASE_REAL_HW                0x400C6000UL
#define NRF_TWIS20_NS_BASE_REAL_HW                0x400C6000UL
#define NRF_UARTE20_NS_BASE_REAL_HW               0x400C6000UL
#define NRF_SPIM20_S_BASE_REAL_HW                 0x500C6000UL
#define NRF_SPIS20_S_BASE_REAL_HW                 0x500C6000UL
#define NRF_TWIM20_S_BASE_REAL_HW                 0x500C6000UL
#define NRF_TWIS20_S_BASE_REAL_HW                 0x500C6000UL
#define NRF_UARTE20_S_BASE_REAL_HW                0x500C6000UL
#define NRF_SPIM21_NS_BASE_REAL_HW                0x400C7000UL
#define NRF_SPIS21_NS_BASE_REAL_HW                0x400C7000UL
#define NRF_TWIM21_NS_BASE_REAL_HW                0x400C7000UL
#define NRF_TWIS21_NS_BASE_REAL_HW                0x400C7000UL
#define NRF_UARTE21_NS_BASE_REAL_HW               0x400C7000UL
#define NRF_SPIM21_S_BASE_REAL_HW                 0x500C7000UL
#define NRF_SPIS21_S_BASE_REAL_HW                 0x500C7000UL
#define NRF_TWIM21_S_BASE_REAL_HW                 0x500C7000UL
#define NRF_TWIS21_S_BASE_REAL_HW                 0x500C7000UL
#define NRF_UARTE21_S_BASE_REAL_HW                0x500C7000UL
#define NRF_SPIM22_NS_BASE_REAL_HW                0x400C8000UL
#define NRF_SPIS22_NS_BASE_REAL_HW                0x400C8000UL
#define NRF_TWIM22_NS_BASE_REAL_HW                0x400C8000UL
#define NRF_TWIS22_NS_BASE_REAL_HW                0x400C8000UL
#define NRF_UARTE22_NS_BASE_REAL_HW               0x400C8000UL
#define NRF_SPIM22_S_BASE_REAL_HW                 0x500C8000UL
#define NRF_SPIS22_S_BASE_REAL_HW                 0x500C8000UL
#define NRF_TWIM22_S_BASE_REAL_HW                 0x500C8000UL
#define NRF_TWIS22_S_BASE_REAL_HW                 0x500C8000UL
#define NRF_UARTE22_S_BASE_REAL_HW                0x500C8000UL
#define NRF_EGU20_NS_BASE_REAL_HW                 0x400C9000UL
#define NRF_EGU20_S_BASE_REAL_HW                  0x500C9000UL
#define NRF_TIMER20_NS_BASE_REAL_HW               0x400CA000UL
#define NRF_TIMER20_S_BASE_REAL_HW                0x500CA000UL
#define NRF_TIMER21_NS_BASE_REAL_HW               0x400CB000UL
#define NRF_TIMER21_S_BASE_REAL_HW                0x500CB000UL
#define NRF_TIMER22_NS_BASE_REAL_HW               0x400CC000UL
#define NRF_TIMER22_S_BASE_REAL_HW                0x500CC000UL
#define NRF_TIMER23_NS_BASE_REAL_HW               0x400CD000UL
#define NRF_TIMER23_S_BASE_REAL_HW                0x500CD000UL
#define NRF_TIMER24_NS_BASE_REAL_HW               0x400CE000UL
#define NRF_TIMER24_S_BASE_REAL_HW                0x500CE000UL
#define NRF_MEMCONF_NS_BASE_REAL_HW               0x400CF000UL
#define NRF_MEMCONF_S_BASE_REAL_HW                0x500CF000UL
#define NRF_PDM20_NS_BASE_REAL_HW                 0x400D0000UL
#define NRF_PDM20_S_BASE_REAL_HW                  0x500D0000UL
#define NRF_PDM21_NS_BASE_REAL_HW                 0x400D1000UL
#define NRF_PDM21_S_BASE_REAL_HW                  0x500D1000UL
#define NRF_PWM20_NS_BASE_REAL_HW                 0x400D2000UL
#define NRF_PWM20_S_BASE_REAL_HW                  0x500D2000UL
#define NRF_PWM21_NS_BASE_REAL_HW                 0x400D3000UL
#define NRF_PWM21_S_BASE_REAL_HW                  0x500D3000UL
#define NRF_PWM22_NS_BASE_REAL_HW                 0x400D4000UL
#define NRF_PWM22_S_BASE_REAL_HW                  0x500D4000UL
#define NRF_SAADC_NS_BASE_REAL_HW                 0x400D5000UL
#define NRF_SAADC_S_BASE_REAL_HW                  0x500D5000UL
#define NRF_NFCT_NS_BASE_REAL_HW                  0x400D6000UL
#define NRF_NFCT_S_BASE_REAL_HW                   0x500D6000UL
#define NRF_TEMP_NS_BASE_REAL_HW                  0x400D7000UL
#define NRF_TEMP_S_BASE_REAL_HW                   0x500D7000UL
#define NRF_P1_NS_BASE_REAL_HW                    0x400D8200UL
#define NRF_P3_NS_BASE_REAL_HW                    0x400D8600UL
#define NRF_P1_S_BASE_REAL_HW                     0x500D8200UL
#define NRF_P3_S_BASE_REAL_HW                     0x500D8600UL
#define NRF_GPIOTE20_NS_BASE_REAL_HW              0x400DA000UL
#define NRF_GPIOTE20_S_BASE_REAL_HW               0x500DA000UL
#define NRF_QDEC20_NS_BASE_REAL_HW                0x400E0000UL
#define NRF_QDEC20_S_BASE_REAL_HW                 0x500E0000UL
#define NRF_QDEC21_NS_BASE_REAL_HW                0x400E1000UL
#define NRF_QDEC21_S_BASE_REAL_HW                 0x500E1000UL
#define NRF_GRTC_NS_BASE_REAL_HW                  0x400E2000UL
#define NRF_GRTC_S_BASE_REAL_HW                   0x500E2000UL
#define NRF_TDM_NS_BASE_REAL_HW                   0x400E8000UL
#define NRF_TDM_S_BASE_REAL_HW                    0x500E8000UL
#define NRF_SPIM23_NS_BASE_REAL_HW                0x400ED000UL
#define NRF_SPIS23_NS_BASE_REAL_HW                0x400ED000UL
#define NRF_TWIM23_NS_BASE_REAL_HW                0x400ED000UL
#define NRF_TWIS23_NS_BASE_REAL_HW                0x400ED000UL
#define NRF_UARTE23_NS_BASE_REAL_HW               0x400ED000UL
#define NRF_SPIM23_S_BASE_REAL_HW                 0x500ED000UL
#define NRF_SPIS23_S_BASE_REAL_HW                 0x500ED000UL
#define NRF_TWIM23_S_BASE_REAL_HW                 0x500ED000UL
#define NRF_TWIS23_S_BASE_REAL_HW                 0x500ED000UL
#define NRF_UARTE23_S_BASE_REAL_HW                0x500ED000UL
#define NRF_SPIM24_NS_BASE_REAL_HW                0x400EE000UL
#define NRF_SPIS24_NS_BASE_REAL_HW                0x400EE000UL
#define NRF_TWIM24_NS_BASE_REAL_HW                0x400EE000UL
#define NRF_TWIS24_NS_BASE_REAL_HW                0x400EE000UL
#define NRF_UARTE24_NS_BASE_REAL_HW               0x400EE000UL
#define NRF_SPIM24_S_BASE_REAL_HW                 0x500EE000UL
#define NRF_SPIS24_S_BASE_REAL_HW                 0x500EE000UL
#define NRF_TWIM24_S_BASE_REAL_HW                 0x500EE000UL
#define NRF_TWIS24_S_BASE_REAL_HW                 0x500EE000UL
#define NRF_UARTE24_S_BASE_REAL_HW                0x500EE000UL
#define NRF_TAMPC_S_BASE_REAL_HW                  0x500EF000UL
#define NRF_SPU30_S_BASE_REAL_HW                  0x50100000UL
#define NRF_DPPIC30_NS_BASE_REAL_HW               0x40102000UL
#define NRF_DPPIC30_S_BASE_REAL_HW                0x50102000UL
#define NRF_PPIB30_NS_BASE_REAL_HW                0x40103000UL
#define NRF_PPIB30_S_BASE_REAL_HW                 0x50103000UL
#define NRF_SPIM30_NS_BASE_REAL_HW                0x40104000UL
#define NRF_SPIS30_NS_BASE_REAL_HW                0x40104000UL
#define NRF_TWIM30_NS_BASE_REAL_HW                0x40104000UL
#define NRF_TWIS30_NS_BASE_REAL_HW                0x40104000UL
#define NRF_UARTE30_NS_BASE_REAL_HW               0x40104000UL
#define NRF_SPIM30_S_BASE_REAL_HW                 0x50104000UL
#define NRF_SPIS30_S_BASE_REAL_HW                 0x50104000UL
#define NRF_TWIM30_S_BASE_REAL_HW                 0x50104000UL
#define NRF_TWIS30_S_BASE_REAL_HW                 0x50104000UL
#define NRF_UARTE30_S_BASE_REAL_HW                0x50104000UL
#define NRF_COMP_NS_BASE_REAL_HW                  0x40106000UL
#define NRF_LPCOMP_NS_BASE_REAL_HW                0x40106000UL
#define NRF_COMP_S_BASE_REAL_HW                   0x50106000UL
#define NRF_LPCOMP_S_BASE_REAL_HW                 0x50106000UL
#define NRF_WDT30_S_BASE_REAL_HW                  0x50108000UL
#define NRF_WDT31_NS_BASE_REAL_HW                 0x40109000UL
#define NRF_WDT31_S_BASE_REAL_HW                  0x50109000UL
#define NRF_P0_NS_BASE_REAL_HW                    0x4010A000UL
#define NRF_P0_S_BASE_REAL_HW                     0x5010A000UL
#define NRF_GPIOTE30_NS_BASE_REAL_HW              0x4010C000UL
#define NRF_GPIOTE30_S_BASE_REAL_HW               0x5010C000UL
#define NRF_CLOCK_NS_BASE_REAL_HW                 0x4010E000UL
#define NRF_POWER_NS_BASE_REAL_HW                 0x4010E000UL
#define NRF_RESET_NS_BASE_REAL_HW                 0x4010E000UL
#define NRF_CLOCK_S_BASE_REAL_HW                  0x5010E000UL
#define NRF_POWER_S_BASE_REAL_HW                  0x5010E000UL
#define NRF_RESET_S_BASE_REAL_HW                  0x5010E000UL
#define NRF_OSCILLATORS_NS_BASE_REAL_HW           0x40120000UL
#define NRF_REGULATORS_NS_BASE_REAL_HW            0x40120000UL
#define NRF_OSCILLATORS_S_BASE_REAL_HW            0x50120000UL
#define NRF_REGULATORS_S_BASE_REAL_HW             0x50120000UL
#define NRF_VREGUSB_NS_BASE_REAL_HW               0x40121000UL
#define NRF_VREGUSB_S_BASE_REAL_HW                0x50121000UL


extern NRF_FICR_Type NRF_FICR_regs;
#undef NRF_FICR_NS_BASE
#define NRF_FICR_NS_BASE (&NRF_FICR_regs)
extern NRF_UICR_Type *NRF_UICR_regs_p[];
#undef NRF_UICR_S_BASE
#define NRF_UICR_S_BASE (NRF_UICR_regs_p[0])
#undef NRF_SICR_S_BASE
#define NRF_SICR_S_BASE NULL
extern NRF_CRACENCORE_Type NRF_CRACENCORE_regs;
#undef NRF_CRACENCORE_S_BASE
#define NRF_CRACENCORE_S_BASE (&NRF_CRACENCORE_regs)
#undef NRF_USBHSCORE_NS_BASE
#define NRF_USBHSCORE_NS_BASE NULL
#undef NRF_USBHSCORE_S_BASE
#define NRF_USBHSCORE_S_BASE NULL
extern NRF_SPU_Type NRF_SPU_regs[];
#undef NRF_SPU00_S_BASE
#define NRF_SPU00_S_BASE (&NRF_SPU_regs[NHW_SPU_00])
#undef NRF_MPC00_S_BASE
#define NRF_MPC00_S_BASE NULL
extern NRF_DPPIC_Type NRF_DPPIC_regs[];
#undef NRF_DPPIC00_NS_BASE
#define NRF_DPPIC00_NS_BASE (&NRF_DPPIC_regs[NHW_DPPI_00])
#undef NRF_DPPIC00_S_BASE
#define NRF_DPPIC00_S_BASE (&NRF_DPPIC_regs[NHW_DPPI_00])
extern NRF_PPIB_Type NRF_PPIB_regs[];
#undef NRF_PPIB00_NS_BASE
#define NRF_PPIB00_NS_BASE (&NRF_PPIB_regs[NHW_PPIB_00])
#undef NRF_PPIB00_S_BASE
#define NRF_PPIB00_S_BASE (&NRF_PPIB_regs[NHW_PPIB_00])
#undef NRF_PPIB01_NS_BASE
#define NRF_PPIB01_NS_BASE (&NRF_PPIB_regs[NHW_PPIB_01])
#undef NRF_PPIB01_S_BASE
#define NRF_PPIB01_S_BASE (&NRF_PPIB_regs[NHW_PPIB_01])
#undef NRF_KMU_S_BASE
#define NRF_KMU_S_BASE NULL
extern NRF_AAR_Type *NRF_AAR_regs[];
extern NRF_CCM_Type *NRF_CCM_regs[];
extern NRF_ECB_Type NRF_ECB_regs[];
#undef NRF_AAR00_NS_BASE
#define NRF_AAR00_NS_BASE (NRF_AAR_regs[NHW_AARCCMECB_00])
#undef NRF_CCM00_NS_BASE
#define NRF_CCM00_NS_BASE (NRF_CCM_regs[NHW_AARCCMECB_00])
#undef NRF_AAR00_S_BASE
#define NRF_AAR00_S_BASE (NRF_AAR_regs[NHW_AARCCMECB_00])
#undef NRF_CCM00_S_BASE
#define NRF_CCM00_S_BASE (NRF_CCM_regs[NHW_AARCCMECB_00])
#undef NRF_ECB00_NS_BASE
#define NRF_ECB00_NS_BASE (&NRF_ECB_regs[NHW_AARCCMECB_00])
#undef NRF_ECB00_S_BASE
#define NRF_ECB00_S_BASE (&NRF_ECB_regs[NHW_AARCCMECB_00])
#undef NRF_VPR00_NS_BASE
#define NRF_VPR00_NS_BASE NULL
#undef NRF_VPR00_S_BASE
#define NRF_VPR00_S_BASE NULL
#undef NRF_SPIM00_NS_BASE
#define NRF_SPIM00_NS_BASE NULL
#undef NRF_SPIS00_NS_BASE
#define NRF_SPIS00_NS_BASE NULL
extern NRF_UARTE_Type NRF_UARTE_regs[];
#undef NRF_UARTE00_NS_BASE
#define NRF_UARTE00_NS_BASE (&NRF_UARTE_regs[NHW_UARTE00])
#undef NRF_SPIM00_S_BASE
#define NRF_SPIM00_S_BASE NULL
#undef NRF_SPIS00_S_BASE
#define NRF_SPIS00_S_BASE NULL
#undef NRF_UARTE00_S_BASE
#define NRF_UARTE00_S_BASE (&NRF_UARTE_regs[NHW_UARTE00])
#undef NRF_GLITCHDET_S_BASE
#define NRF_GLITCHDET_S_BASE NULL
extern void* nhw_RRAMC_get_RRAM_base_address(unsigned int inst);
#define NRF_RRAM_BASE_ADDR ((uintptr_t)nhw_RRAMC_get_RRAM_base_address(0))
extern NRF_RRAMC_Type *NRF_RRAMC_regs_p[];
#undef NRF_RRAMC_S_BASE
#define NRF_RRAMC_S_BASE (NRF_RRAMC_regs_p[0])
extern NRF_GPIO_Type NRF_GPIO_regs[];
#undef NRF_P2_NS_BASE
#define NRF_P2_NS_BASE (&NRF_GPIO_regs[NHW_GPIO_P2])
#undef NRF_P2_S_BASE
#define NRF_P2_S_BASE (&NRF_GPIO_regs[NHW_GPIO_P2])
#undef NRF_CTRLAP_NS_BASE
#define NRF_CTRLAP_NS_BASE NULL
#undef NRF_CTRLAP_S_BASE
#define NRF_CTRLAP_S_BASE NULL
#undef NRF_TAD_NS_BASE
#define NRF_TAD_NS_BASE NULL
#undef NRF_TAD_S_BASE
#define NRF_TAD_S_BASE NULL
extern NRF_TIMER_Type NRF_TIMER_regs[];
#undef NRF_TIMER00_NS_BASE
#define NRF_TIMER00_NS_BASE (&NRF_TIMER_regs[NHW_TIMER_00])
#undef NRF_TIMER00_S_BASE
#define NRF_TIMER00_S_BASE (&NRF_TIMER_regs[NHW_TIMER_00])
extern NRF_EGU_Type NRF_EGU_regs[];
#undef NRF_EGU00_NS_BASE
#define NRF_EGU00_NS_BASE (&NRF_EGU_regs[NHW_EGU_00])
#undef NRF_EGU00_S_BASE
#define NRF_EGU00_S_BASE (&NRF_EGU_regs[NHW_EGU_00])
extern NRF_CRACEN_Type NRF_CRACEN_regs;
#undef NRF_CRACEN_S_BASE
#define NRF_CRACEN_S_BASE (&NRF_CRACEN_regs)
#undef NRF_USBHS_NS_BASE
#define NRF_USBHS_NS_BASE NULL
#undef NRF_USBHS_S_BASE
#define NRF_USBHS_S_BASE NULL
#undef NRF_SPU10_S_BASE
#define NRF_SPU10_S_BASE  (&NRF_SPU_regs[NHW_SPU_10])
#undef NRF_DPPIC10_NS_BASE
#define NRF_DPPIC10_NS_BASE (&NRF_DPPIC_regs[NHW_DPPI_10])
#undef NRF_DPPIC10_S_BASE
#define NRF_DPPIC10_S_BASE (&NRF_DPPIC_regs[NHW_DPPI_10])
#undef NRF_PPIB10_NS_BASE
#define NRF_PPIB10_NS_BASE (&NRF_PPIB_regs[NHW_PPIB_10])
#undef NRF_PPIB10_S_BASE
#define NRF_PPIB10_S_BASE (&NRF_PPIB_regs[NHW_PPIB_10])
#undef NRF_PPIB11_NS_BASE
#define NRF_PPIB11_NS_BASE (&NRF_PPIB_regs[NHW_PPIB_11])
#undef NRF_PPIB11_S_BASE
#define NRF_PPIB11_S_BASE (&NRF_PPIB_regs[NHW_PPIB_11])
#undef NRF_TIMER10_NS_BASE
#define NRF_TIMER10_NS_BASE (&NRF_TIMER_regs[NHW_TIMER_10])
#undef NRF_TIMER10_S_BASE
#define NRF_TIMER10_S_BASE (&NRF_TIMER_regs[NHW_TIMER_10])
#undef NRF_EGU10_NS_BASE
#define NRF_EGU10_NS_BASE (&NRF_EGU_regs[NHW_EGU_10])
#undef NRF_EGU10_S_BASE
#define NRF_EGU10_S_BASE (&NRF_EGU_regs[NHW_EGU_10])
extern NRF_RADIO_Type NRF_RADIO_regs;
#undef NRF_RADIO_NS_BASE
#define NRF_RADIO_NS_BASE (&NRF_RADIO_regs)
#undef NRF_RADIO_S_BASE
#define NRF_RADIO_S_BASE (&NRF_RADIO_regs)
#undef NRF_SPU20_S_BASE
#define NRF_SPU20_S_BASE (&NRF_SPU_regs[NHW_SPU_20])
#undef NRF_DPPIC20_NS_BASE
#define NRF_DPPIC20_NS_BASE (&NRF_DPPIC_regs[NHW_DPPI_20])
#undef NRF_DPPIC20_S_BASE
#define NRF_DPPIC20_S_BASE (&NRF_DPPIC_regs[NHW_DPPI_20])
#undef NRF_PPIB20_NS_BASE
#define NRF_PPIB20_NS_BASE (&NRF_PPIB_regs[NHW_PPIB_20])
#undef NRF_PPIB20_S_BASE
#define NRF_PPIB20_S_BASE (&NRF_PPIB_regs[NHW_PPIB_20])
#undef NRF_PPIB21_NS_BASE
#define NRF_PPIB21_NS_BASE (&NRF_PPIB_regs[NHW_PPIB_21])
#undef NRF_PPIB21_S_BASE
#define NRF_PPIB21_S_BASE (&NRF_PPIB_regs[NHW_PPIB_21])
#undef NRF_PPIB22_NS_BASE
#define NRF_PPIB22_NS_BASE (&NRF_PPIB_regs[NHW_PPIB_22])
#undef NRF_PPIB22_S_BASE
#define NRF_PPIB22_S_BASE (&NRF_PPIB_regs[NHW_PPIB_22])
#undef NRF_SPIM20_NS_BASE
#define NRF_SPIM20_NS_BASE NULL
#undef NRF_SPIS20_NS_BASE
#define NRF_SPIS20_NS_BASE NULL
#undef NRF_TWIM20_NS_BASE
#define NRF_TWIM20_NS_BASE NULL
#undef NRF_TWIS20_NS_BASE
#define NRF_TWIS20_NS_BASE NULL
#undef NRF_UARTE20_NS_BASE
#define NRF_UARTE20_NS_BASE (&NRF_UARTE_regs[NHW_UARTE20])
#undef NRF_SPIM20_S_BASE
#define NRF_SPIM20_S_BASE NULL
#undef NRF_SPIS20_S_BASE
#define NRF_SPIS20_S_BASE NULL
#undef NRF_TWIM20_S_BASE
#define NRF_TWIM20_S_BASE NULL
#undef NRF_TWIS20_S_BASE
#define NRF_TWIS20_S_BASE NULL
#undef NRF_UARTE20_S_BASE
#define NRF_UARTE20_S_BASE (&NRF_UARTE_regs[NHW_UARTE20])
#undef NRF_SPIM21_NS_BASE
#define NRF_SPIM21_NS_BASE NULL
#undef NRF_SPIS21_NS_BASE
#define NRF_SPIS21_NS_BASE NULL
#undef NRF_TWIM21_NS_BASE
#define NRF_TWIM21_NS_BASE NULL
#undef NRF_TWIS21_NS_BASE
#define NRF_TWIS21_NS_BASE NULL
#undef NRF_UARTE21_NS_BASE
#define NRF_UARTE21_NS_BASE (&NRF_UARTE_regs[NHW_UARTE21])
#undef NRF_SPIM21_S_BASE
#define NRF_SPIM21_S_BASE NULL
#undef NRF_SPIS21_S_BASE
#define NRF_SPIS21_S_BASE NULL
#undef NRF_TWIM21_S_BASE
#define NRF_TWIM21_S_BASE NULL
#undef NRF_TWIS21_S_BASE
#define NRF_TWIS21_S_BASE NULL
#undef NRF_UARTE21_S_BASE
#define NRF_UARTE21_S_BASE (&NRF_UARTE_regs[NHW_UARTE21])
#undef NRF_SPIM22_NS_BASE
#define NRF_SPIM22_NS_BASE NULL
#undef NRF_SPIS22_NS_BASE
#define NRF_SPIS22_NS_BASE NULL
#undef NRF_TWIM22_NS_BASE
#define NRF_TWIM22_NS_BASE NULL
#undef NRF_TWIS22_NS_BASE
#define NRF_TWIS22_NS_BASE NULL
#undef NRF_UARTE22_NS_BASE
#define NRF_UARTE22_NS_BASE (&NRF_UARTE_regs[NHW_UARTE22])
#undef NRF_SPIM22_S_BASE
#define NRF_SPIM22_S_BASE NULL
#undef NRF_SPIS22_S_BASE
#define NRF_SPIS22_S_BASE NULL
#undef NRF_TWIM22_S_BASE
#define NRF_TWIM22_S_BASE NULL
#undef NRF_TWIS22_S_BASE
#define NRF_TWIS22_S_BASE NULL
#undef NRF_UARTE22_S_BASE
#define NRF_UARTE22_S_BASE (&NRF_UARTE_regs[NHW_UARTE22])
#undef NRF_EGU20_NS_BASE
#define NRF_EGU20_NS_BASE (&NRF_EGU_regs[NHW_EGU_20])
#undef NRF_EGU20_S_BASE
#define NRF_EGU20_S_BASE (&NRF_EGU_regs[NHW_EGU_20])
#undef NRF_TIMER20_NS_BASE
#define NRF_TIMER20_NS_BASE (&NRF_TIMER_regs[NHW_TIMER_20])
#undef NRF_TIMER20_S_BASE
#define NRF_TIMER20_S_BASE (&NRF_TIMER_regs[NHW_TIMER_20])
#undef NRF_TIMER21_NS_BASE
#define NRF_TIMER21_NS_BASE (&NRF_TIMER_regs[NHW_TIMER_21])
#undef NRF_TIMER21_S_BASE
#define NRF_TIMER21_S_BASE (&NRF_TIMER_regs[NHW_TIMER_21])
#undef NRF_TIMER22_NS_BASE
#define NRF_TIMER22_NS_BASE (&NRF_TIMER_regs[NHW_TIMER_22])
#undef NRF_TIMER22_S_BASE
#define NRF_TIMER22_S_BASE (&NRF_TIMER_regs[NHW_TIMER_22])
#undef NRF_TIMER23_NS_BASE
#define NRF_TIMER23_NS_BASE (&NRF_TIMER_regs[NHW_TIMER_23])
#undef NRF_TIMER23_S_BASE
#define NRF_TIMER23_S_BASE (&NRF_TIMER_regs[NHW_TIMER_23])
#undef NRF_TIMER24_NS_BASE
#define NRF_TIMER24_NS_BASE (&NRF_TIMER_regs[NHW_TIMER_24])
#undef NRF_TIMER24_S_BASE
#define NRF_TIMER24_S_BASE (&NRF_TIMER_regs[NHW_TIMER_24])
#undef NRF_MEMCONF_NS_BASE
#define NRF_MEMCONF_NS_BASE NULL
#undef NRF_MEMCONF_S_BASE
#define NRF_MEMCONF_S_BASE NULL
#undef NRF_PDM20_NS_BASE
#define NRF_PDM20_NS_BASE NULL
#undef NRF_PDM20_S_BASE
#define NRF_PDM20_S_BASE NULL
#undef NRF_PDM21_NS_BASE
#define NRF_PDM21_NS_BASE NULL
#undef NRF_PDM21_S_BASE
#define NRF_PDM21_S_BASE NULL
#undef NRF_PWM20_NS_BASE
#define NRF_PWM20_NS_BASE NULL
#undef NRF_PWM20_S_BASE
#define NRF_PWM20_S_BASE NULL
#undef NRF_PWM21_NS_BASE
#define NRF_PWM21_NS_BASE NULL
#undef NRF_PWM21_S_BASE
#define NRF_PWM21_S_BASE NULL
#undef NRF_PWM22_NS_BASE
#define NRF_PWM22_NS_BASE NULL
#undef NRF_PWM22_S_BASE
#define NRF_PWM22_S_BASE NULL
#undef NRF_SAADC_NS_BASE
#define NRF_SAADC_NS_BASE NULL
#undef NRF_SAADC_S_BASE
#define NRF_SAADC_S_BASE NULL
extern NRF_NFCT_Type NRF_NFCT_regs;
#undef NRF_NFCT_NS_BASE
#define NRF_NFCT_NS_BASE (&NRF_NFCT_regs)
#undef NRF_NFCT_S_BASE
#define NRF_NFCT_S_BASE (&NRF_NFCT_regs)
extern NRF_TEMP_Type NRF_TEMP_regs;
#undef NRF_TEMP_NS_BASE
#define NRF_TEMP_NS_BASE (&NRF_TEMP_regs)
#undef NRF_TEMP_S_BASE
#define NRF_TEMP_S_BASE (&NRF_TEMP_regs)
#undef NRF_P1_NS_BASE
#define NRF_P1_NS_BASE (&NRF_GPIO_regs[NHW_GPIO_P1])
#undef NRF_P1_S_BASE
#define NRF_P1_S_BASE (&NRF_GPIO_regs[NHW_GPIO_P1])
#undef NRF_P3_NS_BASE
#define NRF_P3_NS_BASE (&NRF_GPIO_regs[NHW_GPIO_P3])
#undef NRF_P3_S_BASE
#define NRF_P3_S_BASE (&NRF_GPIO_regs[NHW_GPIO_P3])
extern NRF_GPIOTE_Type NRF_GPIOTE_regs[];
#undef NRF_GPIOTE20_NS_BASE
#define NRF_GPIOTE20_NS_BASE (&NRF_GPIOTE_regs[NHW_GPIOTE_20])
#undef NRF_GPIOTE20_S_BASE
#define NRF_GPIOTE20_S_BASE (&NRF_GPIOTE_regs[NHW_GPIOTE_20])
#undef NRF_QDEC20_NS_BASE
#define NRF_QDEC20_NS_BASE NULL
#undef NRF_QDEC20_S_BASE
#define NRF_QDEC20_S_BASE NULL
#undef NRF_QDEC21_NS_BASE
#define NRF_QDEC21_NS_BASE NULL
#undef NRF_QDEC21_S_BASE
#define NRF_QDEC21_S_BASE NULL
extern NRF_GRTC_Type NRF_GRTC_regs;
#undef NRF_GRTC_NS_BASE
#define NRF_GRTC_NS_BASE (&NRF_GRTC_regs)
#undef NRF_GRTC_S_BASE
#define NRF_GRTC_S_BASE (&NRF_GRTC_regs)
#undef NRF_TDM_NS_BASE
#define NRF_TDM_NS_BASE NULL
#undef NRF_TDM_S_BASE
#define NRF_TDM_S_BASE NULL
#undef NRF_SPIM23_NS_BASE
#define NRF_SPIM23_NS_BASE NULL
#undef NRF_SPIS23_NS_BASE
#define NRF_SPIS23_NS_BASE NULL
#undef NRF_TWIM23_NS_BASE
#define NRF_TWIM23_NS_BASE NULL
#undef NRF_TWIS23_NS_BASE
#define NRF_TWIS23_NS_BASE NULL
#undef NRF_UARTE23_NS_BASE
#define NRF_UARTE23_NS_BASE (&NRF_UARTE_regs[NHW_UARTE23])
#undef NRF_SPIM23_S_BASE
#define NRF_SPIM23_S_BASE NULL
#undef NRF_SPIS23_S_BASE
#define NRF_SPIS23_S_BASE NULL
#undef NRF_TWIM23_S_BASE
#define NRF_TWIM23_S_BASE NULL
#undef NRF_TWIS23_S_BASE
#define NRF_TWIS23_S_BASE NULL
#undef NRF_UARTE23_S_BASE
#define NRF_UARTE23_S_BASE (&NRF_UARTE_regs[NHW_UARTE23])
#undef NRF_SPIM24_NS_BASE
#define NRF_SPIM24_NS_BASE NULL
#undef NRF_SPIS24_NS_BASE
#define NRF_SPIS24_NS_BASE NULL
#undef NRF_TWIM24_NS_BASE
#define NRF_TWIM24_NS_BASE NULL
#undef NRF_TWIS24_NS_BASE
#define NRF_TWIS24_NS_BASE NULL
#undef NRF_UARTE24_NS_BASE
#define NRF_UARTE24_NS_BASE (&NRF_UARTE_regs[NHW_UARTE24])
#undef NRF_SPIM24_S_BASE
#define NRF_SPIM24_S_BASE NULL
#undef NRF_SPIS24_S_BASE
#define NRF_SPIS24_S_BASE NULL
#undef NRF_TWIM24_S_BASE
#define NRF_TWIM24_S_BASE NULL
#undef NRF_TWIS24_S_BASE
#define NRF_TWIS24_S_BASE NULL
#undef NRF_UARTE24_S_BASE
#define NRF_UARTE24_S_BASE (&NRF_UARTE_regs[NHW_UARTE24])
#undef NRF_TAMPC_S_BASE
#define NRF_TAMPC_S_BASE NULL
#undef NRF_SPU30_S_BASE
#define NRF_SPU30_S_BASE (&NRF_SPU_regs[NHW_SPU_30])
#undef NRF_DPPIC30_NS_BASE
#define NRF_DPPIC30_NS_BASE (&NRF_DPPIC_regs[NHW_DPPI_30])
#undef NRF_DPPIC30_S_BASE
#define NRF_DPPIC30_S_BASE (&NRF_DPPIC_regs[NHW_DPPI_30])
#undef NRF_PPIB30_NS_BASE
#define NRF_PPIB30_NS_BASE (&NRF_PPIB_regs[NHW_PPIB_30])
#undef NRF_PPIB30_S_BASE
#define NRF_PPIB30_S_BASE (&NRF_PPIB_regs[NHW_PPIB_30])
#undef NRF_SPIM30_NS_BASE
#define NRF_SPIM30_NS_BASE NULL
#undef NRF_SPIS30_NS_BASE
#define NRF_SPIS30_NS_BASE NULL
#undef NRF_TWIM30_NS_BASE
#define NRF_TWIM30_NS_BASE NULL
#undef NRF_TWIS30_NS_BASE
#define NRF_TWIS30_NS_BASE NULL
#undef NRF_UARTE30_NS_BASE
#define NRF_UARTE30_NS_BASE (&NRF_UARTE_regs[NHW_UARTE20])
#undef NRF_SPIM30_S_BASE
#define NRF_SPIM30_S_BASE NULL
#undef NRF_SPIS30_S_BASE
#define NRF_SPIS30_S_BASE NULL
#undef NRF_TWIM30_S_BASE
#define NRF_TWIM30_S_BASE NULL
#undef NRF_TWIS30_S_BASE
#define NRF_TWIS30_S_BASE NULL
#undef NRF_UARTE30_S_BASE
#define NRF_UARTE30_S_BASE (&NRF_UARTE_regs[NHW_UARTE30])
#undef NRF_COMP_NS_BASE
#define NRF_COMP_NS_BASE NULL
#undef NRF_LPCOMP_NS_BASE
#define NRF_LPCOMP_NS_BASE NULL
#undef NRF_COMP_S_BASE
#define NRF_COMP_S_BASE NULL
#undef NRF_LPCOMP_S_BASE
#define NRF_LPCOMP_S_BASE NULL
#undef NRF_WDT30_S_BASE
#define NRF_WDT30_S_BASE NULL
#undef NRF_WDT31_NS_BASE
#define NRF_WDT31_NS_BASE NULL
#undef NRF_WDT31_S_BASE
#define NRF_WDT31_S_BASE NULL
#undef NRF_P0_NS_BASE
#define NRF_P0_NS_BASE (&NRF_GPIO_regs[NHW_GPIO_P0])
#undef NRF_P0_S_BASE
#define NRF_P0_S_BASE (&NRF_GPIO_regs[NHW_GPIO_P0])
#undef NRF_GPIOTE30_NS_BASE
#define NRF_GPIOTE30_NS_BASE (&NRF_GPIOTE_regs[NHW_GPIOTE_30])
#undef NRF_GPIOTE30_S_BASE
#define NRF_GPIOTE30_S_BASE (&NRF_GPIOTE_regs[NHW_GPIOTE_30])
extern NRF_CLOCK_Type *NRF_CLOCK_regs[];
#undef NRF_CLOCK_NS_BASE
#define NRF_CLOCK_NS_BASE (NRF_CLOCK_regs[NHW_CLKPWR_0])
extern NRF_POWER_Type *NRF_POWER_regs[];
#undef NRF_POWER_NS_BASE
#define NRF_POWER_NS_BASE (NRF_POWER_regs[NHW_CLKPWR_0])
extern NRF_RESET_Type *NRF_RESET_regs[];
#undef NRF_RESET_NS_BASE
#define NRF_RESET_NS_BASE (NRF_RESET_regs[NHW_CLKPWR_0])
#undef NRF_CLOCK_S_BASE
#define NRF_CLOCK_S_BASE (NRF_CLOCK_regs[NHW_CLKPWR_0])
#undef NRF_POWER_S_BASE
#define NRF_POWER_S_BASE (NRF_POWER_regs[NHW_CLKPWR_0])
#undef NRF_RESET_S_BASE
#define NRF_RESET_S_BASE (NRF_RESET_regs[NHW_CLKPWR_0])
extern NRF_OSCILLATORS_Type NRF_OSCILLATORS_regs;
#undef NRF_OSCILLATORS_NS_BASE
#define NRF_OSCILLATORS_NS_BASE (&NRF_OSCILLATORS_regs)
#undef NRF_REGULATORS_NS_BASE
#define NRF_REGULATORS_NS_BASE NULL
#undef NRF_OSCILLATORS_S_BASE
#define NRF_OSCILLATORS_S_BASE (&NRF_OSCILLATORS_regs)
#undef NRF_REGULATORS_S_BASE
#define NRF_REGULATORS_S_BASE NULL
#undef NRF_VREGUSB_NS_BASE
#define NRF_VREGUSB_NS_BASE NULL
#undef NRF_VREGUSB_S_BASE
#define NRF_VREGUSB_S_BASE NULL
